// Code generated by goctl. DO NOT EDIT.
// Source: goods.proto

package server

import (
	"context"

	"2106A-zg6/srv/goods/internal/logic"
	"2106A-zg6/srv/goods/internal/svc"
	"2106A-zg6/srv/goods/pb"
)

type GoodsServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedGoodsServiceServer
}

func NewGoodsServiceServer(svcCtx *svc.ServiceContext) *GoodsServiceServer {
	return &GoodsServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *GoodsServiceServer) Add(ctx context.Context, in *pb.AddReq) (*pb.GoodsEmpty, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}

func (s *GoodsServiceServer) Update(ctx context.Context, in *pb.UpdateReq) (*pb.GoodsEmpty, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

func (s *GoodsServiceServer) Get(ctx context.Context, in *pb.GetReq) (*pb.GetResp, error) {
	l := logic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}

func (s *GoodsServiceServer) Delete(ctx context.Context, in *pb.DeleteReq) (*pb.GoodsEmpty, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}

func (s *GoodsServiceServer) Find(ctx context.Context, in *pb.FindReq) (*pb.FindResp, error) {
	l := logic.NewFindLogic(ctx, s.svcCtx)
	return l.Find(in)
}

func (s *GoodsServiceServer) FindByIds(ctx context.Context, in *pb.FindByIDsReq) (*pb.FindResp, error) {
	l := logic.NewFindByIdsLogic(ctx, s.svcCtx)
	return l.FindByIds(in)
}

func (s *GoodsServiceServer) UpdateStock(ctx context.Context, in *pb.UpdateStockReq) (*pb.GoodsEmpty, error) {
	l := logic.NewUpdateStockLogic(ctx, s.svcCtx)
	return l.UpdateStock(in)
}

func (s *GoodsServiceServer) UpdateStockBack(ctx context.Context, in *pb.UpdateStockReq) (*pb.GoodsEmpty, error) {
	l := logic.NewUpdateStockBackLogic(ctx, s.svcCtx)
	return l.UpdateStockBack(in)
}

func (s *GoodsServiceServer) SearchGoods(ctx context.Context, in *pb.SearchGoodsReq) (*pb.SearchGoodsResp, error) {
	l := logic.NewSearchGoodsLogic(ctx, s.svcCtx)
	return l.SearchGoods(in)
}
