// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Nickname string `json:"nickname"`
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type AddGoodReq struct {
	Name  string  `json:"name"`
	Price float64 `json:"price"`
	Stock int64   `json:"stock"`
}

type SearchGoodsReq struct {
	Content string `json:"content"`
	Limit   int64  `json:"limit"`
	Offset  int64  `json:"offset"`
}

type UpdateGoodReq struct {
}

type GetGoodReq struct {
	Id int64 `json:"id"`
}

type DeleteGoodReq struct {
	Id int64 `json:"id"`
}

type FindGoodsReq struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type GoodsList struct {
	Id       int64 `json:"id"`
	Quantity int64 `json:"quantity"`
}

type CreateOrderReq struct {
	UID   int64       `json:"uid"`
	Goods []GoodsList `json:"goods"`
}

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}
